config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {
  registrations: 'users/registrations'
}

root 'items#index'
devise_scope :user do
  get 'mypage' => 'users/registrations#mypage'
  get 'logout_page' => 'users/registrations#logout_page'
  get 'profile' => 'users/registrations#profile'
  post 'profile' => 'users/registrations#update'
  get 'destination' => 'users/registrations#destination'
  post 'destination' => 'users/registrations#update'
  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'items/items/new' => 'items#new'
end

namespace :items do
  resources :searches, only: :index
end
resources :items, only: [:index, :show,:new,:create,:destroy, :edit, :update] do
  
    collection do
      get 'genre_children', defaults: { format: 'json' }
      get 'genre_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'search'
      get 'genre_children', defaults: { format: 'json' }
      get 'genre_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :purchase, only: [:index,:new,:show]

  resources :items do
    resources :comments, only: :create
  end

resources :creditcards, only:[:index, :new, :create,:destroy,:show] do
  member do
    post 'pay'
  end
  collection do
    post 'delete', to: 'creditcards#delete'
  end
end

end

app/models/creditcard.rb
class Creditcard < ApplicationRecord

  belongs_to :user
  
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  require 'payjp'

  before_action :login_check, only: [:index,:show,:pay,:delete]
  before_action :set_item, only:[:show,:pay]
  before_action :take_card, only:[:index,:show,:pay,:delete]
  before_action :set_api_key
  before_action :correct_user, only:[:show]

  def index
    if @creditcard.blank?
      #登録された情報がない場合にカード登録画面に移動
      flash[:notice] = 'カード情報を登録してください'
      redirect_to new_creditcard_path and return
    else
      #保管した顧客IDでpayjpから情報取得
      set_customer
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      set_card_information
    end

  end

  def show 
    if @creditcard.blank?
      #登録された情報がない場合にカード登録画面に移動
      flash[:alert] = '購入前にカード登録してください'
      redirect_to new_creditcard_path and return
    else
      #保管した顧客IDでpayjpから情報取得
      set_customer
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      set_card_information
    end
    # if current_user.address == nil
    #     flash[:alert] = '購入前に住所登録してください'
    #     redirect_to new_address_path
    # end
  end

  def create
    if params['payjp-token'].blank?
      redirect_to action: "new"
      # トークンが取得出来てなければループ
    else
      user_id = current_user.id
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      # params['payjp-token']（response.id）からcustomerを作成
      ) 
      @card = Creditcard.new(user_id: user_id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        flash[:notice] = '登録しました'
        redirect_to "/"
      else
        flash[:alert] = '登録できませんでした'
        redirect_to action: "new"
      end
    end
  end

  def pay
    @item.update(buyer_id: current_user.id)
    # 現在のユーザーを購入者に登録
    Payjp::Charge.create(
    :amount => @item.price, 
    :customer => @creditcard.customer_id, 
    :currency => 'jpy', #日本円
   )
    redirect_to root_path
  # ホーム画面に遷移
  end

  def delete #PayjpとCardデータベースを削除します
    
    if @creditcard.present?
      set_customer
      @customer.delete
      @creditcard.delete
    end
      redirect_to action: "new"
  end

private

  def correct_user
    @item = Item.find(params[:id])
      if @item.buyer_id == nil
      else 
        redirect_to(root_url) and return 
      end
      if @item.seller_id == current_user.id
        redirect_to(root_path) and return
      end  
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_api_key
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
  end

  def set_customer
    @customer = Payjp::Customer.retrieve(@creditcard.customer_id)
  end

  def set_card_information
    @creditcard_information = @customer.cards.retrieve(@creditcard.card_id)
  end

  def take_card
    @creditcard = Creditcard.find_by(user_id: current_user.id)
  end

  def login_check
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to new_user_session_path
    end
  end

end

app/views/creditcards/_selection.html.haml
.mypage__content__payment
  %h3 支払い方法
.mypage__content__selection
  .mypage__content__selection__box
    %h4 クレジットカード
    %ul
      %li
        %p
          = "**** **** **** " + @creditcard_information.last4
        %p
          - exp_month = @creditcard_information.exp_month.to_s
          - exp_year = @creditcard_information.exp_year.to_s.slice(2,3)
          = "有効期限  " + exp_month + "/" + exp_year
      = form_tag(delete_creditcards_path, method: "POST", id: 'charge-form', name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button 削除する
    -# .change-creditcard
    -#   = link_to "新規カードを登録する", new_creditcard_path

app/views/creditcards/index.html.haml
%header.pcHeader
  =render 'items/header'

.mypage
  .mypage__content
    = render 'selection'

  .mypage__bottom
    = render 'devise/registrations/mypage__bottom'

%aside.appBanner
  .inner
    %h2.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード
    .innner__icon        
      =link_to "#", class: "aBtn" do
        = image_tag 'icon/Download_on_the_App_Store_Badge_JP_blk_.png'
      =link_to "#", class: "gBtn" do
        = image_tag "icon/google-play-badge.png"
        
.home-footer
  = render 'items/top-footer'

app/views/creditcards/new.html.haml
%header.pcHeader
  =render 'items/header'

.mypage
  .mypage__content
    .mypage__content__card
      %h3 クレジットカード情報入力
    .mypage__content__card__info
      = form_with model: @creditcard, url: creditcards_path, local: true, html: { name: 'inputForm' } do |f| 
        .field
          .field-label
            = f.label 'カード番号'
            %span.field-required 必須
          .field-input
            = f.text_field :card_number, id: "card_number",class: "card_form",maxlength: '16', placeholder: "半角数字のみ", autofocus: true
        .field
          .field-label
            = f.label '有効期限'
            %span.field-required 必須
          .field-input_flex
            .flex-input
              = f.collection_select :exp_month , ExpMonth.all, :id, :name 
            .leftbox
              = f.collection_select :exp_year, ExpYear.all, :id, :name
        .field
          .field-label
            =f.label 'セキュリティーコード'
            %span.field-required 必須
          .field-input
            = f.password_field :cvc, id: 'cvc',class: "card_form" ,maxlength: '6', placeholder: "カード背面4桁もしくは3桁の番号"
        #card_token.actions
          = f.submit '登録', id: 'token_submit', class: "btn"

  .mypage__bottom
    = render 'devise/registrations/mypage__bottom'

%aside.appBanner
  .inner
    %h2.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード
    .innner__icon        
      =link_to "#", class: "aBtn" do
        = image_tag 'icon/Download_on_the_App_Store_Badge_JP_blk_.png'
      =link_to "#", class: "gBtn" do
        = image_tag "icon/google-play-badge.png"
        
%footer.home-footer
  = render 'items/top-footer'

app/views/creditcards/show.html.haml
.header
  .header__logo
    =link_to root_path do
      = image_tag 'logo/logo.png',class: "top-icon" 
 
.show-main
  .top
    .top__name 
      購入内容の確認
  .contents
    .contents__item
      .contents__item--image
        -# = image_tag 'purchase/test.jpg',class: "main-item"
        = image_tag @item.images[0],class: "main-item"
      .contents__item--name
        = @item.name
      .contenst__item--price
        送料込み（税込）¥
        = @item.price
    .contents__payment
      .contents__payment--price
        支払い金額: ¥
        = @item.price
      .contents__payment--method
        %h3 支払い方法
        %h4 クレジットカード
        %ul
          %li
            %p
              = "**** **** **** " + @creditcard_information.last4
            %p
              - exp_month = @creditcard_information.exp_month.to_s
              - exp_year = @creditcard_information.exp_year.to_s.slice(2,3)
              = "有効期限  " + exp_month + "/" + exp_year
      .contents__payment--delivery
        %h3 配送先
        %p
          = "〒" + current_user.destination.postal_code 
        %p
          - @prefecture = Prefecture.find current_user.destination.prefecture_id
          = @prefecture.name + current_user.destination.city + current_user.destination.street_block
        %p
          = current_user.destination.destination_family_name_kana + current_user.destination.destination_first_name_kana
    .contents__btn
      .contents__btn--alert
        -# 配送先と支払い方法の入力を完了してください。
      .contents__btn--gray
        .a
        = link_to "購入する", {controller: "creditcards", action: "pay"}, method: :post
    .footer
      .footer__text
        .footer__text--a
          プライバシーポリシー
        .footer__text--b
          フリマ利用規約
        .footer__text--c
          特定商取引に関する表記
      .footer__logo
        =link_to root_path do
          = image_tag 'logo/logo.png',class: "footer-icon" 