config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {
  registrations: 'users/registrations'
}

root 'items#index'
devise_scope :user do
  get 'mypage' => 'users/registrations#mypage'
  get 'logout_page' => 'users/registrations#logout_page'
  get 'profile' => 'users/registrations#profile'
  post 'profile' => 'users/registrations#update'
  get 'destination' => 'users/registrations#destination'
  post 'destination' => 'users/registrations#update'
  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'items/items/new' => 'items#new'
end

namespace :items do
  resources :searches, only: :index
end
resources :items, only: [:index, :show,:new,:create,:destroy, :edit, :update] do
  
    collection do
      get 'genre_children', defaults: { format: 'json' }
      get 'genre_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'search'
      get 'genre_children', defaults: { format: 'json' }
      get 'genre_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :purchase, only: [:index,:new,:show]

  resources :items do
    resources :comments, only: :create
  end

resources :creditcards, only:[:index, :new, :create,:destroy,:show] do
  member do
    post 'pay'
  end
  collection do
    post 'delete', to: 'creditcards#delete'
  end
end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :images
  belongs_to :genre
  has_many :reviews, dependent: :destroy
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, optional: true, class_name: "User"

  validate :images_presence
  validates :name, :introduction, :genre_id, :condition_id, :delivery_fee_id, :pref_id, :day_id, :seller_id, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :pref, presence: true
  belongs_to_active_hash :condition, presence: true
  belongs_to_active_hash :delivery_fee, presence: true
  belongs_to_active_hash :day, presence: true

  def images_presence
    if images.attached?
      # inputに保持されているimagesがあるかを確認
      if images.length > 10
        errors.add(:image, '10枚まで投稿できます')
      end
    else
      errors.add(:image, '画像がありません')
    end
  end

  def self.search(search)
    if search
      return Item.all unless search
      Item.where('name LIKE(?)',"%#{search}%")
    end
  end
end

app/controllers/items/searches_controller.rb
class Items::SearchesController < ApplicationController
  def index
    @items = Item.search(params[:key])
    @search = params[:key]
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :login_check, only: [:new, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @genre_parents = Genre.where("ancestry is null")
    @items = Item.limit(5).order(created_at: :desc)
    #ホームページのピックアップに記載される情報は商品名・価格・画像のみ
  end

  def new
    @item = Item.new
    @genre_parent =  Genre.where("ancestry is null")
  end
  # 親ジャンルが選択された後に動くアクション

  def genre_children
    @genre_children = Genre.find("#{params[:parent_id]}").children
    #親ジャンルに紐付く子ジャンルを取得
  end

  # 子ジャンルが選択された後に動くアクション
  
  def genre_grandchildren
    @genre_grandchildren = Genre.find("#{params[:child_id]}").children
    #子ジャンルに紐付く孫ジャンルの配列を取得
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      flash.now[:alert] = '出品できませんでした'
      render :new
    end
  end

  # 商品詳細表示のアクション
  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @destination = Destination.find_by(user_id: @item.seller_id)
  end

  # 商品編集のアクション
  def edit
    if current_user.id == @item.seller_id
      @genre_parent =  Genre.where("ancestry is null")
    else
      redirect_to root_path
    end
  end

  def update
    if  params[:item][:image_ids].present?
      params[:item][:image_ids].each do |image_id|
        image = @item.images.find(image_id)
        image.purge
      end
    end
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      flash.now[:alert] = '更新できませんでした'
      render :edit
    end
  end
      
  # 商品削除のアクション
  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  # 商品検索のアクション
  def search
    @items = Item.search(params[:key])
    if params[:key] == ""
      redirect_to '/items/search?utf8=✓&keyword=+++'
    end

    if @items.count == 0
      @all_items = Item.limit(25).order("id DESC")
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :brand, :condition_id, :delivery_fee_id, :pref_id, :day_id, :price, images: []).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def login_check
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to new_user_session_path
    end
  end

end

app/views/items/_footer.html.haml
%ul.contents
  %li.content
    %h2.content__head
      FURIMAについて
    %ul
      %li
        %a{:href => "#"}
          会社概要(運営会社)
      %li
        %a{:href => "#"}
          プライバシーポリシー
      %li          
        %a{:href => "#"}
          FURIMA利用規約
      %li
        %a{:href => "#"}
          ポイントに関する特約

  %li.content
    %h2.content__head
      FURIMAを見る
    %ul
      %li
        %a{:href => "#"}
          カテゴリー一覧
      %li
        %a{:href => "#"}
          ブランド一覧

  %li.content
    %h2.content__head
      ヘルプ＆ガイド
    %ul
      %li
        %a{:href => "#"}
          FURIMAガイド
      %li
        %a{:href => "#"}
          FURIMAロゴ利用ガイドライン
      %li
        %a{:href => "#"}
          お知らせ
      
.footerlogo
  %a{:href => "/"}
    = image_tag 'logo/logo-white.png'
  %p
    ©︎ FURIMA

    

app/views/items/_header.html.haml
.headerInner
  .mainHeader
    %h1.icon  
      =link_to "/",class: "top-icon" do
        = image_tag 'logo/logo.png'
    .serchBox
      = form_with url: items_searches_path, local: true, method: :get, class: "serchBox__input" do |form|
        = form.text_field :key, placeholder: "キーワードから探す", class: "searchBox__input",id: "searchInput"
        %button{:type => "submit"}
          .searchBox__icon
            =image_tag 'icon/icon-search 1.png'
        %input{:type => "hidden", :name => "authenticity_token", :value => "#"}  

  .nav
    %ul.listsLeft
      %li.listsLeft__item--first
        = link_to "カテゴリー", "#" ,id: "Btn" 
        .listLeft__item__first__displayNone
          %ul.listLeft__item__displayNone__categoryTree
            %li.listLeft__item__first__displayNone__categoryTree__item

      %li.listsLeft__item
        = link_to "ブランド", "#" ,id: "Btn" 
        %ul.brandsPulldown-displayNone

    %ul.listsRight
      -if user_signed_in?
        %li.listsRight__item
          = link_to "マイページ", mypage_path , id: "Btn"
        %li.listsRight__item
          = link_to "ログアウト", users_sign_out_path, method: :delete, id: "Btn"
      - else
        %li.listsRight__item
          = link_to "ログイン", new_user_session_path,  id: "Btn" 
        %li.listsRight__item
          = link_to "新規会員登録", new_user_registration_path, id: "Btn" 

app/views/items/_middle_main.html.haml
%section.topMiddleDl
  .topMiddleDl__inner
    %h2.subtitle
      会員数日本一位
    %p.text
      FURIMAは、フリマアプリで最も人気。
      %br
        出品・購入回数も業界最多です! 
        %br
          ほしかったあの商品に出会えるかもしれません。
    .btn
      =link_to "#", class: "aBtn" do
        = image_tag 'icon/Download_on_the_App_Store_Badge_JP_blk_.png'
      =link_to "#", class: "gBtn" do
        = image_tag "icon/google-play-badge.png"

%section.topKeyFeatures
  %h2.head
    FURIMAの特徴
  .items
    %section.item
      %figure.item__img
        = image_tag "icon/icon-01.png"
      %h3.item__subtitle
        簡単に売り買いできる
      %p.item__detail
        スマホ一つで、いつでもどこでも簡単に出品・購入が可能!
    %section.item
      %figure.item__img
        = image_tag "icon/icon-03.png"
      %h3.item__subtitle
        売上金は即日振り込みに対応
      %p.item__detail
        午前9時までに振り込みを依頼いただければ、翌日に指定の口座に入金いたします!
    %section.item
      %figure.item__img
        = image_tag "icon/icon-04.png"
      %h3.item__subtitle
        様々な支払いに対応
      %p.item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/items/_top-footer.html.haml
%ul.home-contents
  %li.home-content
    %h2.home-content__head
      FURIMAについて
    %ul
      %li
        =link_to "会社概要(運営会社)", "#" ,class: "botbtn"         
      %li
        =link_to "プライバシーポリシー", "#" ,class: "botbtn"
      %li
        =link_to "FURIMA利用規約","#",class: "botbtn"           
      %li
        =link_to "ポイントに関する特約", "#" ,class: "botbtn"

  %li.home-content
    %h2.home-content__head
      FURIMAを見る
    %ul
      %li
        =link_to "カテゴリー一覧", "#" ,class: "botbtn"
      %li
        =link_to "ブランド一覧", "#" ,class: "botbtn"

  %li.home-content
    %h2.home-content__head
      ヘルプ＆ガイド
    %ul
      %li
        =link_to "FURIMAガイド", "#" ,class: "botbtn"
      %li
        =link_to "FURIMAロゴ利用ガイドライン", "#" ,class: "botbtn"
      %li
        =link_to "お知らせ", "#" ,class: "botbtn"
      
.footerlogo
  =link_to  "#" ,class: "botlogo" do
    = image_tag 'logo/logo-white.png'
  %p
    ©︎ FURIMA

    

app/views/items/_under_main.html.haml
%section.pickupContainer
  %h2.head
    ピックアップカテゴリー
  .productBox
    .productBox__productHead
      .productBox__productHead__pickup
        %h3.productBox__productHead__pickup__title
          新規投稿
    .productBox__productLists
      - @items.each do |item|
        .productBox__productLists__productList
          =link_to item_path(item.id) ,class: "productBox__productLists__productList__goodsshow" do
            %figure.productBox__productLists__productList__goodsshow__image
            -ft_images = item.images
            =image_tag item.images[0], class: "productBox__productLists__productList__goodsshow__itemsphoto"
            -if item.buyer_id.present?
              .productBox__productLists__productList__goodsshow__itemsphoto__sold
                .productBox__productLists__productList__goodsshow__itemsphoto__sold__inner
                  SOLD
            .productBox__productLists__productList__body
              %h3.name
                =item.name
              .details
                %ul
                  %li.price
                    =item.price
                    ="円"
                  %li
                    %i.far.fa-star
                      1
                %p.tax
                  (税込)

%section.pickupContainer
  %h2.head
    ピックアップブランド
  .productBox
    .productBox__productHead
      .productBox__productHead__pickup
        %h3.productBox__productHead__pickup__title
          アーカイバ
    .productBox__productLists
      - @items.each do |item|
        .productBox__productLists__productList
          =link_to item_path(item.id) ,class: "productBox__productLists__productList__goodsshow" do
            %figure.productBox__productLists__productList__goodsshow__image
            -ft_images = item.images
            =image_tag item.images[0], class: "productBox__productLists__productList__goodsshow__itemsphoto"
            -if item.buyer_id.present?
              .productBox__productLists__productList__goodsshow__itemsphoto__sold
                .productBox__productLists__productList__goodsshow__itemsphoto__sold__inner
                  SOLD
            .productBox__productLists__productList__body
              %h3.name
                =item.name
              .details
                %ul
                  %li.price
                    =item.price
                    ="円"
                  %li
                    %i.far.fa-star
                      1
                %p.tax
                  (税込)

app/views/items/_upper_main.html.haml
%section.mainVisual
  .content
    %h2.subtitle
      %br
        人生を変えるフリマアプリ
    %p.text
      FURIMAはだれでもかんたんに出品・購入できる
      %br
        フリマアプリです
    .btn
      =link_to "#", class: "aBtn" do
        = image_tag 'icon/Download_on_the_App_Store_Badge_JP_blk_.png'
      =link_to "#", class: "gBtn" do
        = image_tag "icon/google-play-badge.png"
  .picture

%section.topIntroduction
  %h2.subtitle
    FURIMAが選ばれる3つの理由
  %ul.lists
    %li.list
      .list__pict
        %span.number
          1
        = image_tag 'pict/pict-reason-01.jpg', class: 'reason'
      %h3.list__text
        %span{style: "color: $blue"}> 3分
        ですぐに出品
      %p.list__description
        スマホで入力するだけで簡単に出品できる!

    %li.list
      .list__pict
        %span.number
          2
        = image_tag "pict/pict-reason-02.jpg", class: 'reason'
      %h3.list__text
        %span{style: "color: $blue"}> シンプル
        で使いやすい
      %p.list__description
        めんどくさい入力は必要なく、検索も購入もスムーズ!

    %li.list
      .list__pict
        %span.number
          3
        =image_tag "pict/pict-reason-03.jpg", class: 'reason'
      %h3.list__text
        手数料
        %span
          業界最安
      %p.list__description
        最大3%でお得に出品&購入!

app/views/items/index.html.haml
%header.pcHeader
  =render 'header'

.main
  =render 'upper_main'
  =render 'middle_main'
  =render 'under_main'

%aside.appBanner
  .inner
    %h2.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード
    .innner__icon        
      =link_to "#", class: "aBtn" do
        = image_tag 'icon/Download_on_the_App_Store_Badge_JP_blk_.png'
      =link_to "#", class: "gBtn" do
        = image_tag "icon/google-play-badge.png"

.home-footer
  = render 'top-footer'
  
=link_to "items/new" do
  .purchaseBtn
    %span.purchaseBtn__text
      出品する
    =image_tag 'icon/icon_camera.png' 

app/views/items/new.html.haml
.sell
  %header.sell-header
    = link_to image_tag('logo.png'), root_path, alt: 'Furima', height: '55', class: 'header-logo'
  %main
    %section.sell-container

      = form_with model: @item, url: items_path,id: "form" do |f|

        -# 画像部分
        .sell-container__content
          .sell-title
            %h3.sell-title__text
              出品画像
              %span.sell-title__require
                必須
          .sell-container__content__max-sheet 最大10枚までアップロードできます
          .sell-container__content__upload
            .sell-container__content__upload__items
              .sell-container__content__upload__items__box
                %ul#output-box
                  %div#image-input
                    = f.label :images, for: "item_images0", class: 'sell-container__content__upload__items__box__label', data: {label_id: 0 } do
                      = f.file_field :images, multiple: true, class: "sell-container__content__upload__items__box__input", id: "item_images0", style: 'display: none;'
                      %pre
                        %i.fas.fa-camera.fa-lg
                        クリックしてファイルをアップロード
          .error-messages#error-image

        -# 商品名部分
        .sell-container__content
          .sell-title
            %h3.sell-title__text
              商品名
              %span.sell-title__require
                必須
          = f.text_field :name, {class:'sell-container__content__name', required: "required", placeholder: '商品名（必須 40文字まで)'}
          .error-messages#error-name

          .sell-title
            %h3.sell-title__text
              商品の説明
              %span.sell-title__require
                必須
          = f.text_area :introduction, {class: 'sell-container__content__description', required: "required", rows: '7', maxlength: '1000', placeholder: text_placeholder}
          -# placeholderでtems_helperを呼び出す
          .sell-container__content__word-count
            %span#word-count
              0
            &#47;1000
          .error-messages#error-text

        -# 詳細部分
        .sell-container__content
          %h3.sell-sub-head 商品の詳細
          .sell-container__content__details
            .sell-title
              %h3.sell-title__text
                カテゴリー
                %span.sell-title__require
                  必須
            .sell-collection_select
              = f.label :genre_id, {class: 'sell-collection_select__label'} do
                = f.collection_select :genre_id, @genre_parent, :id, :name, {prompt: "選択して下さい"},{ class: 'sell-collection_select__input', id: 'genre-select', required: "required"}
                %i.fas.fa-chevron-down
            .error-messages#error-genre

            
            .sell-title
              %h3.sell-title__text
                ブランド
                %span.sell-title__require__common
                  任意
            = f.text_field :brand, {class:'sell-container__content__brand', placeholder: '例）シャネル'}
            .error-messages#error-brand

            .sell-title
              %h3.sell-title__text
                商品の状態
                %span.sell-title__require
                  必須
            .sell-collection_select
              = f.label :condition_id, {class: 'sell-collection_select__label'} do
                = f.collection_select :condition_id, Condition.all, :id, :condition, {prompt: '選択して下さい'},{ class: 'sell-collection_select__input', id: 'condition-select', required: "required"}
                %i.fas.fa-chevron-down
            .error-messages#error-condition

        -# 配送部分
        .sell-container__content
          %h3.sell-sub-head
            %p 配送について
            = link_to '#',target: '_blank',class: 'sell-sub-head__guides-link' do
              %i.far.fa-question-circle
          .sell-container__content__delivery
            .sell-title
              %h3.sell-title__text
                配送料の負担
                %span.sell-title__require
                  必須
            .sell-collection_select
              = f.label :delivery_fee_id, {class: 'sell-collection_select__label'} do
                = f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :payer, {prompt: '選択して下さい'},{ class: 'sell-collection_select__input', id: 'delivery_fee-select', required: "required"}
                %i.fas.fa-chevron-down
            .error-messages#error-delivery_fee

            .sell-title
              %h3.sell-title__text
                発送元の地域
                %span.sell-title__require
                  必須
            .sell-collection_select
              = f.label :pref_id, class: 'sell-collection_select__label' do
                = f.collection_select :pref_id, Pref.all, :id, :name, {prompt: '選択して下さい'},{ class: 'sell-collection_select__input', id: 'pref-select', required: "required"}
                %i.fas.fa-chevron-down
            .error-messages#error-pref

            .sell-title
              %h3.sell-title__text
                発送までの日数
                %span.sell-title__require
                  必須
            .sell-collection_select
              = f.label :day_id, class: 'sell-collection_select__label' do
                = f.collection_select :day_id, Day.all, :id, :day, {prompt: '選択して下さい'},{ class: 'sell-collection_select__input', id: 'day-select', required: "required"}
                %i.fas.fa-chevron-down
            .error-messages#error-day

        -# 価格部分
        .sell-container__content
          %h3.sell-sub-head
            %p 販売価格(300〜9,999,999)
            = link_to '/price',target: '_blank', class: 'sell-sub-head__guides-link' do
              %i.far.fa-question-circle
          .sell-container__content__price
            .sell-title
              %h3.sell-title__text
                販売価格
                %span.sell-title__require
                  必須
            .sell-container__content__price__form
              = f.label :price, class: 'sell-container__content__price__form__label' do
                ¥
                = f.number_field :price, {placeholder: '0', value: '', autocomplete:"off", class: 'sell-container__content__price__form__box', required: "required"}
          .error-messages#error-price

          .sell-container__content__commission
            .sell-container__content__commission__left
              販売手数料 （10%）
            .sell-container__content__commission__right ー
          .sell-container__content__profit
            .sell-container__content__profit__left
              販売利益
            .sell-container__content__profit__right ー
          
          .submit-btn
            = f.submit '出品する', class: 'submit-btn__sell-btn'
            = link_to 'もどる', root_path, class: 'submit-btn__return-btn'
          .attention-box
            %p
              禁止されている行為および出品物を必ずご確認ください。偽ブランド品や
              盗品物などの販売は犯罪であり、法律により処罰される可能性があります。また、出品をもちまして
              加盟店規約に同意したことになります。

  %footer.sell-footer
    %nav
      %ul.clearfix
        %li
          = link_to '#' do
            プライバシーポリシー
        %li
          = link_to '#' do
            利用規約
        %li
          = link_to '#' do
            特定商取引に関する表記
    = link_to root_path, class: 'footer__logo' do
      = image_tag 'logo-white.png', alt: 'Furima', height: '45', class: 'footer__logo__image'
    %p
      %small
        &copy; Furima, Inc.

app/views/items/search.html.haml
.search
  %header.pcHeader
    =render 'header'

  %main.search-container
    .l-content
      %section.items-box-container
        %h1.search-result-head
          検索結果




  %footer.home-footer
    = render 'top-footer'
    
  =link_to "items/new" do
    .purchaseBtn
      %span.purchaseBtn__text
        出品する
      =image_tag 'icon/icon_camera.png' 

app/views/items/show.html.haml
/header
%header.pcHeader
  =render 'items/header'

/パンくずは追加実装

/main
.main
  .showMain
    .contentRight
      .topContent
        .itembox
          %h2.itembox__name
            =@item.name
          .itembox__body
            %ul
              %li
                = image_tag @item.images[0]
                -if @item.images.length > 5
                  %ul
                    -for i in 0..4
                      %li
                        = image_tag @item.images[i]
                  %ul
                    -@item.images.each.with_index do |image,count|
                      -if count < 5
                      -else
                        %li
                          = image_tag image
                -else
                  %ul
                    -@item.images.each do |image|
                      %li
                        =image_tag image

          .itembox__price
            %span
              ¥
              =@item.price
          .itembox__price-detail
            %span
              （税込）
            %span
              送料込み
          -if @item.buyer_id != nil
            .itembtnarea
              %button.soldBtn{type: "submit",name: "button"}
                売り切れました
          - else
          -if user_signed_in? && current_user.id != @item.seller_id && @item.buyer_id.nil?
            .itembtnarea
              %button.buyBtn{type: "submit",name: "button"}
                = link_to "商品購入", creditcard_path
          - else
          -if user_signed_in? && current_user.id == @item.seller_id && @item.buyer_id.nil?
            .itembtnarea__seller
              %button.editBtn{type: "submit",name: "button"}
                = link_to edit_item_path(@item) do
                  編集
              %button.deleteBtn
                = link_to '削除',item_path, method: :delete, data: { confirm: '削除してよろしいですか?' }
          -else
          .itemdetail
            =@item.introduction
          
          .table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    =@destination.nickname
                %tr
                  %th
                    カテゴリー
                  %td
                    %a
                      = link_to '#' do
                        =@item.genre.root.name
                        %br
                        =@item.genre.parent.name
                        %br
                        =@item.genre.name
                %tr
                  %th
                    ブランド
                  %td
                    =@item.brand
                %tr
                  %th
                    商品の状態
                  %td
                    =@item.condition.condition
                %tr
                  %th
                    配送料の負担
                  %td
                    =@item.delivery_fee.payer
                %tr
                  %th
                    発送元の地域
                  %td
                    %a
                      = link_to '#' do
                        =@item.pref.name
                %tr
                  %th
                    発送日の目安
                  %td
                    =@item.day.day
          .option
            %ul
              %li.option__btn
                %i.fa.fa-star
                  お気に入り
            %ul.optional
              %li.optionalBtn
                %a
                  %i.fa.fa-flag
                  = link_to "不適切な商品の通報", "#"
      
          
          .commentBox
            - if user_signed_in?
              %ul.commentContets
                = form_with model:[@item, @comment] ,class:"textarea", local: true do |f|
                  = f.text_area :comment,id: "comment_body",rows: "2",placeholder: "コメントする"
                  = f.submit "コメントする",class:"commentBtn"
            - else
              %strong
                %p
                  ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
             

          .comments
            %h4 ＜コメント一覧＞
            - if @comments
              - @comments.each do |comment|
                %p
                  %strong
                    = link_to comment.user.family_name
                  %span :
                  = comment.comment

      %ul.links
        %li.test-link
          %a
            %i.fa.fa-angle-left
            = link_to "前の商品", "#"
        %li
          %a
            = link_to "後ろの商品", "#"
            %i.fa.fa-angle-right

      .relatedItems
        %a
          = link_to "レディースをもっと見る", "#"


/footer
%aside.appBanner
  .inner
    %h2.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード
    .innner__icon        
      =link_to "#", class: "aBtn" do
        = image_tag 'icon/Download_on_the_App_Store_Badge_JP_blk_.png'
      =link_to "#", class: "gBtn" do
        = image_tag "icon/google-play-badge.png"

.home-footer
  = render 'items/top-footer'